-- IEK Connect Hub: cuentas, roles y estado académico personal sincronizado.
-- Ejecutar en Supabase SQL Editor o mediante `supabase db push`.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'student' check (role in ('student', 'admin', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_app_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{"version":1,"values":{},"updatedAt":{}}'::jsonb,
  revision bigint not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_state_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  state jsonb not null,
  source text not null check (source in ('local-before-merge', 'cloud-before-merge', 'manual')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.user_app_state enable row level security;
alter table public.user_state_backups enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.user_app_state from anon, authenticated;
revoke all on public.user_state_backups from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name) on public.profiles to authenticated;
grant select, insert, update, delete on public.user_app_state to authenticated;
grant select, insert, delete on public.user_state_backups to authenticated;
grant usage, select on sequence public.user_state_backups_id_seq to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select to authenticated using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "state_select_own" on public.user_app_state;
create policy "state_select_own" on public.user_app_state
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "state_insert_own" on public.user_app_state;
create policy "state_insert_own" on public.user_app_state
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "state_update_own" on public.user_app_state;
create policy "state_update_own" on public.user_app_state
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "state_delete_own" on public.user_app_state;
create policy "state_delete_own" on public.user_app_state
  for delete to authenticated using (user_id = auth.uid());

drop policy if exists "backups_select_own" on public.user_state_backups;
create policy "backups_select_own" on public.user_state_backups
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "backups_insert_own" on public.user_state_backups;
create policy "backups_insert_own" on public.user_state_backups
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "backups_delete_own" on public.user_state_backups;
create policy "backups_delete_own" on public.user_state_backups
  for delete to authenticated using (user_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, nullif(trim(coalesce(new.raw_user_meta_data->>'display_name', '')), ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
  for each row execute procedure public.touch_updated_at();

drop trigger if exists user_app_state_touch_updated_at on public.user_app_state;
create trigger user_app_state_touch_updated_at before update on public.user_app_state
  for each row execute procedure public.touch_updated_at();

-- El usuario puede borrar definitivamente su propia cuenta sin exponer la
-- service_role al navegador. La función solo acepta auth.uid().
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;
